# Generated by Django 2.0.4 on 2018-04-21 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('websiteAddress', models.CharField(max_length=200)),
                ('role', models.CharField(choices=[('Bachelorstudent', 'Bachelorstudent'), ('Masterstudent', 'Masterstudent'), ('Alumnus', 'Alumnus'), ('Other', 'Other')], default='Alumnus', max_length=100)),
                ('additionalMessage', models.TextField(blank=True)),
            ],
        ),
    ]
