# Generated by Django 2.0.4 on 2018-04-21 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0003_auto_20180421_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='takePart',
            field=models.BooleanField(default=False),
        ),
    ]
