# Generated by Django 2.0.4 on 2018-04-28 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0006_auto_20180425_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='artwork1Price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='artwork1SizeH',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='artwork1SizeW',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='artwork2Price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='artwork2SizeH',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='artwork2SizeW',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='artwork3Price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='artwork3SizeH',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='artwork3SizeW',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
