# Generated by Django 2.0.4 on 2018-05-09 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0007_auto_20180428_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='role',
            field=models.CharField(choices=[('Bachelorstudent', 'Bachelor student'), ('Masterstudent', 'Master student'), ('Alumnus', 'Alumnus'), ('Other', 'Other')], default='Alumnus', max_length=20),
        ),
    ]
