# Generated by Django 2.0.4 on 2018-05-10 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0009_auto_20180509_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='artwork1Price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='artwork2Price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='artwork3Price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
