# Generated by Django 2.0.4 on 2018-04-20 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendee',
            name='isAttending',
        ),
        migrations.AddField(
            model_name='attendee',
            name='additionalMessage',
            field=models.CharField(blank=True, max_length=6000),
        ),
        migrations.AddField(
            model_name='attendee',
            name='role',
            field=models.CharField(choices=[('Bachelorstudent', 'Bachelorstudent'), ('Masterstudent', 'Masterstudent'), ('Alumnus', 'Alumnus'), ('Other', 'Other')], default='Bachelorstudent', max_length=6),
        ),
        migrations.AddField(
            model_name='attendee',
            name='websiteAddress',
            field=models.CharField(default='www.example.com', max_length=200),
        ),
    ]
