# Generated by Django 2.0.4 on 2018-04-20 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0002_auto_20180420_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='additionalMessage',
            field=models.TextField(blank=True),
        ),
    ]
