# Generated by Django 2.0.4 on 2018-04-20 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0003_auto_20180420_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='role',
            field=models.CharField(choices=[('Bachelorstudent', 'Bachelorstudent'), ('Masterstudent', 'Masterstudent'), ('Alumnus', 'Alumnus'), ('Other', 'Other')], default='Bachelorstudent', max_length=100),
        ),
    ]
