# Generated by Django 2.0.4 on 2018-04-21 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0004_auto_20180420_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='websiteAddress',
            field=models.CharField(max_length=200),
        ),
    ]
